import { Hono, type Context } from 'hono'
import { isSafeStorageKey } from '@/lib/storage/keys'
import { selectStorageAdapter } from '@/lib/storage/select-adapter'
import type { AppVariables } from '../src/types'

// -----------------------------------------------------------------------------
// GET /api/v1/files/:key — public file serving for uploaded MUN assets
// -----------------------------------------------------------------------------
//
// Serves logos, covers, gallery images and PDF documents uploaded through
// lib/actions/mun-branding.ts and lib/actions/mun-documents.ts. Mounted in
// server/src/app.ts at /api/v1/files.
//
// Access model: anyone who has the URL can fetch the file. Keys are
// `muns/<munId>/<area>/<random UUID>`, generated by the server, so a URL
// can't be guessed, only learned from the documents/media list endpoints.
// Those lists are meant to be public for published MUNs. Until the
// published-or-owner guards on them land, a draft MUN's file URLs are
// discoverable by anyone who knows its id. Nothing private (delegate
// uploads, ID documents) goes through this route yet; when it does, it needs
// an authorization check here, not just an unguessable key.
//
// Response headers:
//   - Content-Type: the stored type, but only if it is one of the types
//     uploads are validated against (lib/storage/validate.ts); anything else
//     is served as an application/octet-stream attachment.
//   - X-Content-Type-Options: nosniff, so browsers never reinterpret a file.
//   - Content-Security-Policy: `default-src 'none'; sandbox` for images.
//     PDFs get `default-src 'none'; object-src 'self'` without `sandbox`: a
//     sandboxed document may not load plugins, and Chrome treats its PDF
//     viewer as one, so the PDF would be blocked instead of shown. Upload
//     validation already guarantees the bytes are a PDF.
//   - Content-Disposition: inline with a filename built from the key.
//   - Cache-Control: one year, immutable. A key is never reused for new
//     bytes, so a cached copy is never stale. A deleted file can live on in
//     browser caches until they expire.
//   - Cross-Origin-Resource-Policy: cross-origin, because the web app
//     (munhub.in and its subdomains) embeds these from api.munhub.in.

const SERVABLE_TYPES: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
}

const IMAGE_CSP = "default-src 'none'; sandbox"
const PDF_CSP = "default-src 'none'; object-src 'self'"
const IMMUTABLE_CACHE = 'public, max-age=31536000, immutable'

export const filesRoutes = new Hono<{ Variables: AppVariables }>()

function notFound(c: Context<{ Variables: AppVariables }>) {
  // no-store: KV is eventually consistent, so a file uploaded seconds ago may
  // not be visible here yet. Don't let a browser remember the miss.
  c.header('Cache-Control', 'no-store')
  return c.json({ error: { code: 'NOT_FOUND', message: 'File not found' } }, 404)
}

filesRoutes.get('/:key{.+}', async (c) => {
  const key = c.req.param('key')
  if (!isSafeStorageKey(key)) return notFound(c)

  const object = await selectStorageAdapter().get(key)
  if (!object) return notFound(c)

  const extension = SERVABLE_TYPES[object.contentType]
  const basename = key.slice(key.lastIndexOf('/') + 1)
  const headers = new Headers({
    'Cache-Control': IMMUTABLE_CACHE,
    'X-Content-Type-Options': 'nosniff',
    'Cross-Origin-Resource-Policy': 'cross-origin',
  })

  if (extension) {
    const filename = basename.endsWith(`.${extension}`) ? basename : `${basename}.${extension}`
    headers.set('Content-Type', object.contentType)
    headers.set('Content-Disposition', `inline; filename="${filename}"`)
    headers.set('Content-Security-Policy', object.contentType === 'application/pdf' ? PDF_CSP : IMAGE_CSP)
  } else {
    headers.set('Content-Type', 'application/octet-stream')
    headers.set('Content-Disposition', `attachment; filename="${basename}"`)
    headers.set('Content-Security-Policy', IMAGE_CSP)
  }

  if (object.sha256) {
    const etag = `"${object.sha256}"`
    headers.set('ETag', etag)
    const ifNoneMatch = c.req.header('If-None-Match')
    if (ifNoneMatch && ifNoneMatch.split(',').some((tag) => tag.trim().replace(/^W\//, '') === etag)) {
      if (object.body instanceof ReadableStream) await object.body.cancel()
      return new Response(null, { status: 304, headers })
    }
  }

  const length = object.body instanceof Uint8Array ? object.body.byteLength : object.size
  headers.set('Content-Length', String(length))
  return new Response(object.body, { status: 200, headers })
})
